In [1]:
import pyrealsense2 as rs2
import open3d as o3d
import numpy as np
import time
from spygrt.stream import Recording, NoMoreFrames, DualRecording
from spygrt.tracker import Tracker


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
rec1 = Recording('E:/VISION/Youssef_Test/Recording_Session/121622061907_2022May24015518.bag')
rec2 = Recording('E:/VISION/Youssef_Test/Recording_Session/123122061443_2022May24015518.bag')
rec1.load_calibration('121622061907_cal.txt')
rec2.load_calibration('123122061443_cal.txt')



array([[-0.84303463, -0.35969847,  0.40744796, -0.41306779],
       [-0.54072845,  0.63098216, -0.56176376,  0.55750799],
       [-0.0548597 , -0.69179678, -0.72423196,  0.68112701],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [3]:
d = DualRecording(rec1,rec2)

In [4]:
d.start_stream()

In [5]:
d.get_frames()

((<pyrealsense2.frame Z16 #8050 @1653364518544.000000>,
  <pyrealsense2.frame RGB8 #8047 @1653364518560.602295>),
 (<pyrealsense2.frame Z16 #8008 @1653364518580.588135>,
  <pyrealsense2.frame RGB8 #8003 @1653364518564.528564>))

In [3]:
d = DualRecording(rec1,rec2)
d.start_stream()
d.get_frames()

RuntimeError: wait_for_frames cannot be called before start()

In [6]:
t = Tracker(ref_surface=d.pcd)

[Open3D INFO] Picked point #291137 (0.082, -0.014, 0.14) to add in queue.
[Open3D INFO] Picked point #1279289 (-0.041, 0.13, 0.19) to add in queue.


In [10]:
d.compute_pcd(True)

PointCloud on CPU:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [18]:
a = time.time()
t.get_motion(d.compute_pcd(True))
b= time.time()

In [7]:
o3d.io.write_point_cloud('ref_pc.pcd', d.pcd.to_legacy())

True

In [7]:
T1 = np.loadtxt('r1_cal.txt')

In [8]:
d.stream1._pose = T1@d.stream1.pose

In [16]:
d.compute_pcd()

PointCloud on CPU:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [18]:
from datetime import timedelta
delta = timedelta(seconds=70)
d.stream1.seek(delta)
d.stream2.seek(delta)

In [19]:
t.get_motion(d.compute_pcd(True))

[[0.999999 0.000828050 0.00148744 -0.000326829],
 [-0.000827450 1.0 -0.000403588 8.04856e-05],
 [-0.00148777 0.000402357 0.999999 -7.19777e-05],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float64, CPU:0, 0x265f6ad0630]

In [21]:
o3d.visualization.draw_geometries([d.pcd.to_legacy()])

In [22]:
d.timestamp

1653364518578.96

In [23]:
a = d.compute_pcd(True)

In [24]:
a is None

False

In [10]:
np.savetxt('1.txt',d.stream1.pose)

In [11]:
d.stream1.serial

'121622061907'

In [ ]:
data = []
for i in range(1000):
    try:
        t.get_motion(d.compute_pcd(True))
        data.append(np.concatenate(([d.timestamp], Tracker.compute_translation(t.t_guess), 
                                    Tracker.compute_rotation(t.t_guess))))
    except:
        print(i)
        
        

Timestamps:1653364520223.93 8100 1653364520093.0332 8053
Timestamps:1653364520425.8904 8106 1653364520294.2217 8059
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
Timestamps:1653364520559.7507 8110 1653364520429.2112 8063
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
78
79
80
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
[Open3D WARNING] Creating from an empty legacy PointCloud.
87
[Open3D WARNING] Creating from an empty legacy PointCloud.
88
[Open3D WARNING] Creating from an empty legacy PointCloud.
89
[Open

[Open3D WARNING] Creating from an empty legacy PointCloud.
199
[Open3D WARNING] Creating from an empty legacy PointCloud.
200
[Open3D WARNING] Creating from an empty legacy PointCloud.
201
[Open3D WARNING] Creating from an empty legacy PointCloud.
202
[Open3D WARNING] Creating from an empty legacy PointCloud.
203
Timestamps:1653364526238.3037 8279 1653364526106.6328 8232
[Open3D WARNING] Creating from an empty legacy PointCloud.
204
[Open3D WARNING] Creating from an empty legacy PointCloud.
205
[Open3D WARNING] Creating from an empty legacy PointCloud.
206
[Open3D WARNING] Creating from an empty legacy PointCloud.
207
[Open3D WARNING] Creating from an empty legacy PointCloud.
208
Timestamps:1653364526506.794 8287 1653364526375.2278 8240
Timestamps:1653364526506.794 8287 1653364526375.2278 8240
[Open3D WARNING] Creating from an empty legacy PointCloud.
209
[Open3D WARNING] Creating from an empty legacy PointCloud.
210
[Open3D WARNING] Creating from an empty legacy PointCloud.
211
[Open3

In [8]:
for i in range(70):
    d.compute_pcd(True)

Timestamps:1653364520223.93 8100 1653364520093.0332 8053


In [13]:
o3d.visualization.draw_geometries([d.pcd.to_legacy()])

In [24]:
d.compute_pcd(True)

Timestamps:1653364520559.7507 8110 1653364520429.2112 8063


PointCloud on CPU:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [25]:
t.get_motion(d.pcd)

[[0.627468 -0.00375678 0.778633 -0.139913],
 [0.119804 0.988547 -0.0917754 -0.0100821],
 [-0.76937 0.150869 0.620732 0.0116034],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float64, CPU:0, 0x1b12c90a010]

In [26]:
box = o3d.geometry.OrientedBoundingBox.create_from_axis_aligned_bounding_box(t._box.to_legacy())
# Commented out as transform is not yet implemented.
# box.transform(self._t_guess.numpy())
box.rotate(t._t_guess.numpy()[0:3].T[0:3].T)
box.translate(t._t_guess.numpy().T[-1][0:3])
source = o3d.t.geometry.PointCloud.from_legacy(d.pcd.to_legacy().crop(box))

In [27]:
o3d.visualization.draw_geometries([source.to_legacy()])