In [1]:
import cv2 as cv
import pyrealsense2 as rs2
import open3d as o3d
import numpy as np
import time

from spygrt.stream import Recording, NoMoreFrames, DualRecording
from spygrt.tracker import Tracker
#rec1 = Recording('C:/Users/yben4607/clean/ResearchData/VISION/Youssef_Test/Recording_Session/121622061907_2022May24015518.bag')
#rec2 = Recording('C:/Users/yben4607/clean/ResearchData/VISION/Youssef_Test/Recording_Session/123122061443_2022May24015518.bag')
#rec1.load_calibration('C:/Users/yben4607/clean/ResearchData/VISION/Youssef_Test/RS_Calibration/121622061907_cal.txt')
#rec2.load_calibration('C:/Users/yben4607/clean/ResearchData/VISION/Youssef_Test/RS_Calibration/123122061443_cal.txt')
rec1 = Recording('E:/VISION/129/Recording_Session/121622061907_2023Feb13022044.bag')
rec2 = Recording('E:/VISION/129/Recording_Session/123122061443_2023Feb13022044.bag')
rec1.load_calibration('121622061907_cal.txt')
rec2.load_calibration('123122061443_cal.txt')


d = DualRecording(rec1,rec2)
d.start_stream()
d.get_frames()

t = Tracker(ref_surface=d.pcd)


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


NoMoreFrames: Reached the end of the stream

In [2]:
d.get_frames()

t = Tracker(ref_surface=d.pcd)


[Open3D INFO] Picked point #195005 (0.089, -0.065, 0.16) to add in queue.
[Open3D INFO] Picked point #189889 (0.087, -0.062, 0.17) to add in queue.
[Open3D INFO] Remove picked point #189889 from pick queue.
[Open3D INFO] Remove picked point #195005 from pick queue.
[Open3D INFO] Picked point #209075 (0.095, -0.071, 0.15) to add in queue.
[Open3D INFO] Picked point #1162800 (-0.031, 0.056, 0.16) to add in queue.


In [3]:
o3d.visualization.draw_geometries([t.ref_surface.to_legacy()])

In [2]:
from datetime import timedelta
delta = timedelta(seconds=70)
d.stream1.seek(delta)
d.stream2.seek(delta)

In [7]:
p1 = [0.3,0.3,0.3]
p2 = [-0.3,-0.3,0.2]
midz = np.mean([p1[2], p2[2]])
lower = [np.min([p1[0], p2[0]]), np.min([p1[1], p2[1]]), midz - 0.02]

In [8]:
 lower

[-0.3, -0.3, 0.23]

In [10]:
type(d.pcd.point['positions'].numpy()[0][0])

numpy.float32

In [5]:
t.get_motion(d.compute_pcd(True))

[[0.999995 -0.000287926 -0.00316072 0.000480056],
 [0.000288454 1.0 0.000166551 6.4272e-05],
 [0.00316067 -0.000167462 0.999995 -3.49351e-05],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float64, CPU:0, 0x1de12c37ef0]

In [7]:
a=d.compute_pcd(True)

In [10]:
a is None

True

In [14]:
d.get_frames()

((<pyrealsense2.frame Z16 #8056 @1653364518745.431152>,
  <pyrealsense2.frame RGB8 #8052 @1653364518728.857178>),
 (<pyrealsense2.frame Z16 #8013 @1653364518748.400391>,
  <pyrealsense2.frame RGB8 #8008 @1653364518732.104736>))

In [15]:
d.pose is None

False

In [18]:
d.stream1.compute_pcd() + d.stream2.compute_pcd()

PointCloud on CPU:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [4]:
t.ref_surface.estimate_normals(30,0.001)

In [8]:
Tracker.compute_rotation(t._t_guess)

AttributeError: type object 'Tracker' has no attribute 'isR_matrix'

In [4]:
data = []
for i in range(12000):
    try:
        t.get_motion(d.compute_pcd(True))
    except RuntimeError:
        continue
    data.append(np.concatenate(([d.timestamp], Tracker.compute_translation(t.t_guess), Tracker.compute_rotation(t.t_guess))))
    if i%100 == 0:
        print(i/100)
        np.savetxt('track.txt',data)
    

0.0
1.0
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
2.0
[Open3D WARNING] 0 correspondence present between the pointclouds. Try increasing the max_correspondence_distance parameter.
Timestamps:1676258453649.446 1442 1676258453771.4412 1406
3.0
Timestamps:1676258454422.1592 1465 1676258454544.2842 1429
Timestamps:1676258455194.96 1488 1676258455317.0886 1452
Timestamps:1676258457782.2197 1565 1676258457904.2498 1529
4.0
Timestamps:1676258458386.9849 1583 1676258458509.0286 1547
5.0
Timestamps:1676258461713.4575 1682 1676258461835.3643 1646
6.0
Timestamps:1676258467996.565 1869 1676258468118.3394 1833
7.0
8.0
Timestamps:1676258473540.3994 2034 1676258473662.154 1998
Timestamps:1676258473910.0315 2045 1676258474031.7454 2009
9.0
Timestamps:1676258475455.641 2091 1676258475577.3076 2055
Timestamps:1676258477774.1038 2160 1676258477660.4612 2117
10.0
Timestamps:1676258479857.305 2222 1676258479743.5542 2179
Time

47.0
Timestamps:1676258607300.6638 6015 1676258607150.695 5971
Timestamps:1676258608913.467 6063 1676258608797.203 6020
Timestamps:1676258609283.0742 6074 1676258609402.0483 6038
Timestamps:1676258610492.6763 6110 1676258610611.5654 6074
48.0
Timestamps:1676258611399.8574 6137 1676258611283.55 6094
Timestamps:1676258611534.254 6141 1676258611653.1375 6105
49.0
Timestamps:1676258615532.6309 6260 1676258615382.6155 6216
Timestamps:1676258616742.2283 6296 1676258616860.887 6260
50.0
Timestamps:1676258617918.1777 6331 1676258618036.844 6295
Timestamps:1676258617918.1777 6331 1676258618036.844 6295
Timestamps:1676258619631.696 6382 1676258619515.2014 6339
Timestamps:1676258620337.2766 6403 1676258620455.95 6367
Timestamps:1676258620337.2766 6403 1676258620455.95 6367
51.0
52.0
Timestamps:1676258625343.5884 6552 1676258625462.3413 6516
Timestamps:1676258625343.5884 6552 1676258625462.3413 6516
Timestamps:1676258625813.9949 6566 1676258625932.6926 6530
Timestamps:1676258625813.9949 6566 16762

In [4]:
o3d.visualization.draw_geometries([t._source.to_legacy()])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 


In [8]:
t.t_guess

[[0.960616 -0.26193 -0.0927886 0.0517465],
 [0.276662 0.932738 0.23121 -0.0737735],
 [0.0259866 -0.247775 0.968469 0.0439792],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float64, CPU:0, 0x24d64541970]

In [7]:
saved_data = data

In [17]:
for i in range(48):
    d.compute_pcd(True)

In [18]:
t.get_motion(d.pcd)

[[0.976428 -0.135231 0.168226 -0.0104739],
 [0.146373 0.987664 -0.0556359 -0.0120752],
 [-0.158627 0.0789482 0.984177 -0.068689],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float64, CPU:0, 0x18e6fd1f110]

In [19]:
o3d.visualization.draw_geometries([t._source.to_legacy()])

In [3]:
np.savetxt('data.txt',np.asarray(data))

In [5]:
d.timestamp

1676258858178.8535

In [4]:
len(data)

496

In [7]:
a=1.676258596709123047e+12
b=1.676258444235704590e+12
a-b

152473.41845703125

In [5]:
import numpy as np
R = np.asarray([[1,2,3,4],[5,6,7,8],[9, 10 ,11, 12],[13,14,15,16]])

In [6]:
R

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
R[0:3].T[0:3].T

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [9]:
(1676258858178.8535-a)/1000/60

4.3578288411458335

In [10]:
np.savetxt('track.txt',data)