In [1]:
from spygrt.stream import Recording, NoMoreFrames, DualRecording
from spygrt.tracker import Tracker
import open3d as o3d
import numpy as np
import datetime
td = datetime.timedelta(seconds=60)


In [3]:
f1 = 'S:/SMART2/RecordingSession1/RecordingSession/121622060739_2023Mar28021735.bag'
f2 = 'S:/SMART2/RecordingSession1/RecordingSession/123122061763_2023Mar28021735.bag'
#f1 = 'S:/SMART1/RecordingSession1/Calibration/121622060739_2023Mar28112520.bag'
#f2 = 'S:/SMART1/RecordingSession1/Calibration/123122061763_2023Mar28112520.bag'

(rec1,rec2) = (Recording(f1),Recording(f2))
rec1.load_calibration('121622060739_cal.txt')
rec2.load_calibration('123122061763_cal.txt')

array([[ 0.72743475,  0.52885199, -0.4023962 ,  0.39200184],
       [ 0.66333687, -0.5420509 ,  0.48675805, -0.56936502],
       [ 0.03989112, -0.63028949, -0.75624883,  0.73373735],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [2]:
rec1 = Recording('E:/VISION/129/OptiTrack_Calibration_Square/121622061907_2023Feb13014913.bag')
rec2 = Recording('E:/VISION/129/OptiTrack_Calibration_Square/123122061443_2023Feb13014913.bag')
rec1.load_calibration('121622061907_cal.txt')
rec2.load_calibration('123122061443_cal.txt')

array([[-0.76596981, -0.47690493,  0.46312463, -0.43199882],
       [-0.65983385,  0.45945311, -0.61818653,  0.47658443],
       [ 0.0808824 , -0.76817775, -0.65726215,  0.49703872],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [3]:
d = DualRecording(rec1,rec2)

In [4]:
d.start_stream()

In [5]:
d.get_frames()

((<pyrealsense2.frame Z16 #11345 @1676256553041.796387>,
  <pyrealsense2.frame RGB8 #11379 @1676256553042.133301>),
 (<pyrealsense2.frame Z16 #11275 @1676256553040.908203>,
  <pyrealsense2.frame RGB8 #11309 @1676256553041.245117>))

In [19]:
rec1.frame[0].timestamp-rec2.frame[0].timestamp

-38.609375

In [39]:
o3d.visualization.draw_geometries([d.pcd.to_legacy()])

In [10]:
o3d.io.write_point_cloud('p1.pcd',rec1.pcd.to_legacy())
o3d.io.write_point_cloud('p2.pcd',rec2.pcd.to_legacy())

True

In [11]:
T1 = np.loadtxt('bg3.txt')

In [12]:
I1 = rec1.pose

In [13]:
rec1._pose = T1@I1

In [14]:
d.compute_pcd(False)

PointCloud on CPU:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [38]:
d.compute_pcd()

PointCloud on CPU:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [21]:
np.savetxt('newcal1.txt',rec1.pose)

In [22]:
rec1.serial

'121622060739'

In [37]:
rec1.load_calibration('121622060739_cal.txt')
rec2.load_calibration('123122061763_cal.txt')

array([[ 0.72743475,  0.52885199, -0.4023962 ,  0.39200184],
       [ 0.66333687, -0.5420509 ,  0.48675805, -0.56936502],
       [ 0.03989112, -0.63028949, -0.75624883,  0.73373735],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [27]:
rec1.compute_pcd()
rec2.compute_pcd()

PointCloud on CPU:0 [921600 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {921600, 3}).

In [28]:
rec1.pose

array([[ 0.7349115 , -0.5298841 ,  0.36219311, -0.49975458],
       [-0.63727158, -0.53680873,  0.50771767, -0.45184904],
       [-0.07645842, -0.61896294, -0.75039655,  0.72218263],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [29]:
T1@I1

array([[ 0.73999778, -0.51848006,  0.36828861, -0.48056263],
       [-0.63042609, -0.52355113,  0.52963897, -0.50501075],
       [-0.08382288, -0.63963147, -0.73205604,  0.69529085],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [30]:
rec1._pose = T1@I1

In [36]:
rec1.serial

'121622060739'

In [22]:
vis = o3d.visualization.VisualizerWithEditing()
vis.create_window()
vis.add_geometry(d.pcd.to_legacy())
vis.run()
vis.destroy_window()
idx = vis.get_picked_points()

[Open3D INFO] Picked point #371834 (-0.0056, 0.0089, 0.02) to add in queue.
[Open3D INFO] Picked point #530740 (-0.012, 0.2, 0.018) to add in queue.


In [8]:
I = np.asarray([[1,0,0,0.022],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [10]:
rec1._pose = I@rec1._pose
rec2._pose = I@rec2._pose

In [21]:
d.compute_pcd(True)

PointCloud on CUDA:0 [1843200 points (Float32)].
Attributes: colors (dtype = UInt8, shape = {1843200, 3}).

In [23]:
I

array([[1.   , 0.   , 0.   , 0.022],
       [0.   , 1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   , 0.   ],
       [0.   , 0.   , 0.   , 1.   ]])