In [9]:
from spygrt.stream import Recording, NoMoreFrames, DualRecording
from spygrt.tracker import Tracker
import spygrt.stream as stream
import open3d as o3d
import numpy as np
import datetime
td = datetime.timedelta(seconds=60)


In [31]:
f1 = 'S:/SMART4/Visit1/RecordingSession/121622060739_2023Apr04123937.bag'
f2 = 'S:/SMART4/Visit1/RecordingSession/123122061763_2023Apr04123937.bag'
#f1 = 'S:/SMART1/RecordingSession1/Calibration/121622060739_2023Mar28112520.bag'
#f2 = 'S:/SMART1/RecordingSession1/Calibration/123122061763_2023Mar28112520.bag'

(rec1,rec2) = (Recording(f1),Recording(f2))
rec1.load_calibration('S:/SMART3/Visit1/Calibration/121622060739_cal.txt')
rec2.load_calibration('S:/SMART3/Visit1/Calibration/123122061763_cal.txt')

array([[-0.46229416, -0.63298768,  0.60097951, -0.53006196],
       [-0.86823386,  0.40326354, -0.24313405,  0.34573084],
       [-0.08955309, -0.64208311, -0.74516785,  0.71987921],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [2]:
rec1 = Recording('E:/VISION/129/OptiTrack_Calibration_Square/121622061907_2023Feb13014913.bag')
rec2 = Recording('E:/VISION/129/OptiTrack_Calibration_Square/123122061443_2023Feb13014913.bag')
rec1.load_calibration('121622061907_opti.txt')
rec2.load_calibration('123122061443_opti.txt')

array([[ 0.76596981,  0.47690493, -0.46312463,  0.40999882],
       [ 0.65983385, -0.45945311,  0.61818653, -0.47658443],
       [ 0.0808824 , -0.76817775, -0.65726215,  0.49703872],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [3]:
rec1.load_calibration('121622061907opti.txt')
rec2.load_calibration('123122061443opti.txt')

array([[-0.76596981, -0.47690493,  0.46312463, -0.40999882],
       [-0.65983385,  0.45945311, -0.61818653,  0.47658443],
       [ 0.0808824 , -0.76817775, -0.65726215,  0.49703872],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [3]:
d = DualRecording(rec1,rec2)

In [4]:
d.start_stream()

In [5]:
d.get_frames()

((<pyrealsense2.frame Z16 #11345 @1676256553041.796387>,
  <pyrealsense2.frame RGB8 #11379 @1676256553042.133301>),
 (<pyrealsense2.frame Z16 #11275 @1676256553040.908203>,
  <pyrealsense2.frame RGB8 #11309 @1676256553041.245117>))

In [37]:
rec1.frame[0].timestamp-rec2.frame[0].timestamp

0.214599609375

In [6]:
frames = rec1.frame

In [41]:
frames

(<pyrealsense2.frame Z16 #653 @1680575977858.764160>,
 <pyrealsense2.frame RGB8 #638 @1680575977873.828857>)

In [7]:
np_depth = np.asanyarray(frames[0].get_data())
np_color = np.asanyarray(frames[1].get_data())

In [10]:
depth = o3d.t.geometry.Image(o3d.core.Tensor(np_depth, device=stream.DEVICE))
color = o3d.t.geometry.Image(o3d.core.Tensor(np_color, device=stream.DEVICE))

In [11]:
o3d.visualization.draw_geometries([im.to_legacy()])

NameError: name 'im' is not defined

In [12]:
rgbdim = o3d.t.geometry.RGBDImage(color,depth)
intrinsics = o3d.core.Tensor(rec1.get_o3d_intrinsics().intrinsic_matrix, device=stream.DEVICE)
pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(rgbdim, intrinsics,depth_scale=1000)

In [66]:
o3d.visualization.draw_geometries([rgbdim.to_legacy()])

In [57]:
rgbdim

RGBD Image pair [Aligned]
Color [size=(1280,720), channels=3, format=UInt8, device=CUDA:0]
Depth [size=(1280,720), channels=1, format=Float64, device=CUDA:0]

In [14]:
vis = o3d.visualization.VisualizerWithEditing()
vis.create_window()
vis.add_geometry(pcd.to_legacy())
vis.run()
vis.destroy_window()
idx = vis.get_picked_points()

[Open3D INFO] Picked point #453690 (0.13, 0.023, 0.67) to add in queue.
[Open3D INFO] Picked point #169615 (-0.0060, -0.081, 0.76) to add in queue.
[Open3D INFO] Picked point #237991 (0.05, -0.025, 0.72) to add in queue.
[Open3D INFO] Picked point #287653 (0.09, 0.0036, 0.69) to add in queue.
[Open3D INFO] Picked point #334207 (0.019, -0.051, 0.74) to add in queue.


AttributeError: 'numpy.ndarray' object has no attribute 'inv'